export const SHOP = {
  name: 'પટેલ નાસ્તા હબ',
  nameLatin: 'Patel Nasta Hub',
  logoSrc: '/images/logo-brand.png',
  tagline: 'સ્વાદ જે દિલ સુધી પહોંચે',
  phoneDisplay: '+91 96648 59253',
  phoneTel: '+919664859253',
  whatsapp: 'https://wa.me/919664859253',
  email: 'Patelnastqhub@gmail.com',
  website: 'https://www.patelnastahub.com',
  addressLines: [
    'છાપરા જી.આઈ.ડી.સી., કાલાવડ રોડ, છાપરા',
    'દેવડા નું પાટિયું, જેસડિયા કોમ્પ્લેક્સ',
  ],
  addressShort: 'છાપરા જી.આઈ.ડી.સી., કાલાવડ રોડ, છાપરા',
  socialHandle: 'patel nasta hub',
  ownerGu: 'સોજીત્રા મધુરેશ વલ્લભભાઈ',
  upiId: 'paytmqr67fjfd@ptys',
  openingHoursGu: 'સવારે 7 વાગ્યાથી રાત્રે 10 વાગ્યા સુધી',
  openingHoursLatin: '7:00 AM – 10:00 PM',
} as const
